FROM valyanskiy/my-ml-base:latest

WORKDIR /app

COPY . .

# Создаем entrypoint скрипт
RUN echo '#!/bin/bash\n\
echo "Проверка моделей..."\n\
python3 download_models.py\n\
echo "Запуск AI сервиса..."\n\
python3 model.py' > /app/entrypoint.sh && chmod +x /app/entrypoint.sh

CMD ["/app/entrypoint.sh"]