FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04 AS base

ENV PYTHONUNBUFFERED=1

# Установи системные deps (кэшируется по умолчанию, пока список не меняется)
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# --- Шаг 1: Копируем ТОЛЬКО requirements.txt и устанавливаем deps ---
# Кэшируется, пока файл не меняется
COPY requirements.txt .
RUN pip3 install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121 && \
    rm -rf /tmp/*  # Очистка

# --- Шаг 2: Копируем остальной код ---
COPY . .

CMD python3 model.py  # Исправлено здесь